#!/bin/bash

build_scheme () {
  scheme="$1"
  docker build -t "$DOCKER_REPO:$DOCKER_TAG-$scheme" --build-arg "TL_SCHEME=$scheme" .
}

build_scheme basic
build_scheme small
build_scheme medium
build_scheme full
