#!/bin/bash

default_scheme="medium"

push_image () {
  suffix="$1"
  docker push "$DOCKER_REPO:$DOCKER_TAG$suffix"
}

docker tag "$DOCKER_REPO:$DOCKER_TAG-$default_scheme" "$DOCKER_REPO:$DOCKER_TAG"

push_image
push_image -basic
push_image -small
push_image -medium
push_image -full
